import Link from "next/link";
import { Bell, Bookmark, BriefcaseBusiness, Eye, Heart, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { CharacterArt } from "@/components/character-art";
import { formatHongKongDate, isPublicLocale, localePath, localizeCharacter, pick } from "@/components/acg-locale";
import { RewardClaimPanel } from "@/components/reward-claim-panel";
import { ShopPanel } from "@/components/shop-panel";
import { SectionHeading } from "@/components/ui/section-heading";
import { currencyLabel } from "@/lib/utils";
import { getPortfolioView, getShopItems } from "@/lib/store";

export const dynamic = "force-dynamic";

export default async function PlayerRoom({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params;
  if (!isPublicLocale(rawLocale)) notFound();
  const locale = rawLocale;
  const [portfolio, shopItems] = await Promise.all([getPortfolioView().catch(() => null), getShopItems(locale)]);
  if (!portfolio) return <div className="exchange-page"><section className="exchange-panel mx-auto max-w-3xl bg-[#111827] p-8 text-center text-white sm:p-14"><UserRound className="mx-auto h-12 w-12 text-[#ffcc66]" /><p className="mt-6 exchange-kicker justify-center text-[#ffcc66] before:hidden">PLAYER ROOM LOCKED</p><h1 className="mt-4 font-display text-5xl">{pick(locale, "Sign in to open your room", "登入後打開你的玩家房間")}</h1><p className="mx-auto mt-5 max-w-xl text-base leading-8 text-white/60">{pick(locale, "Your wallet, favorite shelves, rewards, work shifts, cosmetics, and privacy settings live here.", "錢包、本命收藏櫃、每日獎勵、角色打工、外觀與隱私設定都會留在這裡。")}</p><Link href="/api/auth/signin" className="exchange-button-primary mt-8">{pick(locale, "Open sign in", "前往登入")}</Link></section></div>;
  const copy = locale === "zh-Hant" ? { eyebrow: "PLAYER ROOM", title: `${portfolio.profile.displayName} 的應援房間`, body: "這是收藏與陪伴的基地，不把你的平均成本或損益當成身份。", wallet: "可用 SUP", public: "查看公開房間", holdingsEyebrow: "FAVORITE SHELF", holdingsTitle: "正在支持的角色", holdingsBody: "角色收藏櫃顯示陪伴與累積應援，不用紅綠損益提醒你比較。", missionEyebrow: "DAILY MISSIONS", missionTitle: "今天的小任務", missionBody: "以真實的正向行動完成任務，不獎勵灌水留言。", watchingEyebrow: "WATCHING", watchingTitle: "留在雷達上的訊號", watchingBody: "先關注，等真正心動的時候再支持。", noticeEyebrow: "NOTIFICATIONS", noticeTitle: "房間裡的新消息", noticeBody: "獎勵、外觀與應援活動集中在這裡。", shopEyebrow: "EQUIPPED COLLECTION", shopTitle: "替房間換上新的心情", shopBody: "已收藏的外觀可以再次裝備；新物品會直接進入你的收藏。" } : { eyebrow: "PLAYER ROOM", title: `${portfolio.profile.displayName}'s support room`, body: "A base for collecting and comfort. Average cost and profit never become your identity here.", wallet: "Available SUP", public: "View public room", holdingsEyebrow: "FAVORITE SHELF", holdingsTitle: "Characters you are supporting", holdingsBody: "The shelf centers companionship and accumulated support, without red or green profit prompts.", missionEyebrow: "DAILY MISSIONS", missionTitle: "Small missions for today", missionBody: "Complete real positive actions. Spam comments never earn rewards.", watchingEyebrow: "WATCHING", watchingTitle: "Signals kept on your radar", watchingBody: "Watch first, then send support when a character truly resonates.", noticeEyebrow: "NOTIFICATIONS", noticeTitle: "New signals in your room", noticeBody: "Rewards, cosmetics, and support activity arrive here.", shopEyebrow: "EQUIPPED COLLECTION", shopTitle: "Give your room a new mood", shopBody: "Equip owned looks again or unlock a new collectible directly into your shelf." };
  const missions = [
    { icon: Heart, en: "React with affection", zh: "送出一次正向反應", reward: "+10", done: true },
    { icon: Bookmark, en: "Watch or support a character", zh: "關注或支持一名角色", reward: "+15", done: portfolio.watchlist.length > 0 || portfolio.positions.length > 0 },
    { icon: Sparkles, en: "Enter a comfort room", zh: "進入一次安慰室", reward: "+20", done: false },
  ];

  return <div className="exchange-page">
    <section className="exchange-panel overflow-hidden bg-[#111827] text-white"><div className="grid lg:grid-cols-[1fr_.92fr]"><div className="p-6 sm:p-10 xl:p-12"><p className="exchange-kicker text-[#ffcc66] before:bg-[#ffcc66]">{copy.eyebrow}</p><h1 className="mt-7 font-display text-5xl leading-none sm:text-6xl">{copy.title}</h1><p className="mt-5 max-w-2xl text-base leading-8 text-white/62">{copy.body}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={localePath(locale, `/u/${portfolio.profile.handle}`)} className="exchange-button-secondary border-white/12 bg-white/6 text-white hover:bg-white/12 hover:text-white"><Eye className="h-4 w-4" />{copy.public}</Link><span className="inline-flex items-center gap-2 rounded-[14px_4px_14px_4px] border border-white/12 px-4 py-3 text-xs font-bold text-white/55"><ShieldCheck className="h-4 w-4 text-[#3ed6e0]" />{pick(locale, "Private wallet · public affection", "錢包私密 · 喜愛可公開")}</span></div></div><div className="grid gap-4 border-t border-white/10 p-6 lg:border-t-0 lg:border-l sm:p-8"><div className="rounded-[22px_5px_22px_5px] bg-gradient-to-br from-[#ff4e72] to-[#ff9f43] p-6"><p className="text-[10px] font-black uppercase tracking-[.2em] text-white/65">{copy.wallet}</p><p className="mt-3 font-display text-5xl">{currencyLabel(portfolio.wallet.softBalance)}</p><p className="mt-4 text-xs leading-6 text-white/65">300 starter · +100 daily · +20 rewarded ad</p></div><RewardClaimPanel locale={locale} /></div></div></section>

    <section className="grid gap-7"><SectionHeading eyebrow={copy.holdingsEyebrow} title={copy.holdingsTitle} description={copy.holdingsBody} />{portfolio.positions.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{portfolio.positions.map((position) => { const character = localizeCharacter(position.character, locale); return <Link key={position.id} href={localePath(locale, `/character/${character.slug}`)} className="exchange-panel group overflow-hidden"><CharacterArt character={character} className="min-h-[300px]" /><div className="relative z-10 p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#e83c62]">{position.units} {pick(locale, "support units", "份應援")}</p><h3 className="mt-2 font-display text-3xl">{character.name}</h3><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-[#ff4e72] to-[#ffcc66]" style={{ width: `${Math.min(100, 28 + position.units * 9)}%` }} /></div></div></Link>; })}</div> : <div className="exchange-panel p-8 text-slate-500">{pick(locale, "Your first favorite is waiting in the signal market.", "你的第一位本命正在訊號市場等你。")}</div>}</section>

    <section className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div className="exchange-panel p-6 sm:p-8"><SectionHeading eyebrow={copy.missionEyebrow} title={copy.missionTitle} description={copy.missionBody} /><div className="mt-7 grid gap-3">{missions.map(({ icon: Icon, en, zh, reward, done }) => <div key={en} className="flex items-center gap-4 rounded-[18px_5px_18px_5px] border border-black/8 bg-[#f5f1e8] p-4"><span className="mission-check">{done ? "✓" : <Icon className="h-4 w-4" />}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-800">{pick(locale, en, zh)}</p><p className="mt-1 text-[10px] font-black uppercase tracking-[.15em] text-slate-400">{done ? pick(locale, "Completed", "已完成") : pick(locale, "In progress", "進行中")}</p></div><span className="font-black text-[#19757a]">{reward}</span></div>)}</div><Link href={localePath(locale, "/work")} className="exchange-button-primary mt-6"><BriefcaseBusiness className="h-4 w-4" />{pick(locale, "Open work dispatch", "打開角色派遣")}</Link></div><div className="exchange-panel bg-[#111827] p-6 text-white sm:p-8"><SectionHeading eyebrow={copy.noticeEyebrow} title={copy.noticeTitle} description={copy.noticeBody} tone="light" /><div className="mt-7 grid gap-3">{portfolio.notifications.map((notice) => <div key={notice.id} className="flex gap-4 rounded-[18px_5px_18px_5px] border border-white/8 bg-white/5 p-4"><Bell className="mt-1 h-4 w-4 shrink-0 text-[#ffcc66]" /><div><p className="text-sm font-bold">{notice.title}</p><p className="mt-2 text-xs leading-6 text-white/50">{notice.body}</p><time className="mt-2 block text-[9px] uppercase tracking-[.14em] text-white/30">{formatHongKongDate(notice.createdAt, locale)}</time></div></div>)}</div></div></section>

    {portfolio.watchlist.length ? <section className="grid gap-7"><SectionHeading eyebrow={copy.watchingEyebrow} title={copy.watchingTitle} description={copy.watchingBody} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{portfolio.watchlist.map((entry) => { const character = localizeCharacter(entry, locale); return <Link key={character.id} href={localePath(locale, `/character/${character.slug}`)} className="exchange-panel group overflow-hidden"><CharacterArt character={character} className="min-h-[240px]" /><div className="p-4"><p className="font-display text-2xl">{character.name}</p></div></Link>; })}</div></section> : null}

    <section className="grid gap-7"><SectionHeading eyebrow={copy.shopEyebrow} title={copy.shopTitle} description={copy.shopBody} /><ShopPanel items={shopItems} inventory={portfolio.inventory} locale={locale} /></section>
  </div>;
}
